void cTheta()
{
//=========Macro generated from canvas: cTheta/Theta distributions
//=========  (Wed Apr  1 14:00:01 2026) by ROOT version 6.24/08
   TCanvas *cTheta = new TCanvas("cTheta", "Theta distributions",1928,112,1920,1080);
   gStyle->SetOptStat(0);
   cTheta->Range(-3.25325,-13.75,29.27925,123.75);
   cTheta->SetFillColor(0);
   cTheta->SetBorderMode(0);
   cTheta->SetBorderSize(2);
   cTheta->SetGridx();
   cTheta->SetGridy();
   cTheta->SetFrameBorderMode(0);
   cTheta->SetFrameBorderMode(0);
   
   Double_t _fx1001[2] = {
   0,
   26};
   Double_t _fy1001[2] = {
   0,
   110};
   Double_t _fex1001[2] = {
   0,
   0};
   Double_t _fey1001[2] = {
   0,
   0};
   TGraphErrors *gre = new TGraphErrors(2,_fx1001,_fy1001,_fex1001,_fey1001);
   gre->SetName("");
   gre->SetTitle("Fission's Detectors' Efficiencies");
   gre->SetFillStyle(1000);
   gre->SetMarkerColor(0);
   gre->SetMarkerStyle(8);
   
   TH1F *Graph_Graph1001 = new TH1F("Graph_Graph1001","Fission's Detectors' Efficiencies",100,0,28.6);
   Graph_Graph1001->SetMinimum(0);
   Graph_Graph1001->SetMaximum(110);
   Graph_Graph1001->SetDirectory(0);
   Graph_Graph1001->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   Graph_Graph1001->SetLineColor(ci);
   Graph_Graph1001->GetXaxis()->SetTitle(" E^{*} (MeV)");
   Graph_Graph1001->GetXaxis()->SetRange(1,91);
   Graph_Graph1001->GetXaxis()->CenterTitle(true);
   Graph_Graph1001->GetXaxis()->SetLabelFont(132);
   Graph_Graph1001->GetXaxis()->SetTitleSize(0.055);
   Graph_Graph1001->GetXaxis()->SetTitleOffset(0.8);
   Graph_Graph1001->GetXaxis()->SetTitleFont(132);
   Graph_Graph1001->GetYaxis()->SetTitle("Efficiency");
   Graph_Graph1001->GetYaxis()->CenterTitle(true);
   Graph_Graph1001->GetYaxis()->SetLabelFont(132);
   Graph_Graph1001->GetYaxis()->SetTitleSize(0.055);
   Graph_Graph1001->GetYaxis()->SetTitleOffset(0.8);
   Graph_Graph1001->GetYaxis()->SetTitleFont(132);
   Graph_Graph1001->GetZaxis()->SetLabelFont(132);
   Graph_Graph1001->GetZaxis()->SetTitleOffset(1);
   Graph_Graph1001->GetZaxis()->SetTitleFont(132);
   gre->SetHistogram(Graph_Graph1001);
   
   gre->Draw("ap");
   
   TH1D *HitRatio_BottomandSide__1 = new TH1D("HitRatio_BottomandSide__1","HitRatio_BottomandSide",21,5,26);
   HitRatio_BottomandSide__1->SetBinContent(1,67);
   HitRatio_BottomandSide__1->SetBinContent(2,74);
   HitRatio_BottomandSide__1->SetBinContent(3,67);
   HitRatio_BottomandSide__1->SetBinContent(4,70);
   HitRatio_BottomandSide__1->SetBinContent(5,69);
   HitRatio_BottomandSide__1->SetBinContent(6,74);
   HitRatio_BottomandSide__1->SetBinContent(7,72);
   HitRatio_BottomandSide__1->SetBinContent(8,65);
   HitRatio_BottomandSide__1->SetBinContent(9,74);
   HitRatio_BottomandSide__1->SetBinContent(10,63);
   HitRatio_BottomandSide__1->SetBinContent(11,65);
   HitRatio_BottomandSide__1->SetBinContent(12,72);
   HitRatio_BottomandSide__1->SetBinContent(13,72);
   HitRatio_BottomandSide__1->SetBinContent(14,67);
   HitRatio_BottomandSide__1->SetBinContent(15,67);
   HitRatio_BottomandSide__1->SetBinContent(16,59);
   HitRatio_BottomandSide__1->SetBinContent(17,64);
   HitRatio_BottomandSide__1->SetBinContent(18,74);
   HitRatio_BottomandSide__1->SetBinContent(19,75);
   HitRatio_BottomandSide__1->SetBinContent(20,65);
   HitRatio_BottomandSide__1->SetBinContent(21,52);
   HitRatio_BottomandSide__1->SetBinError(1,67);
   HitRatio_BottomandSide__1->SetBinError(2,74);
   HitRatio_BottomandSide__1->SetBinError(3,67);
   HitRatio_BottomandSide__1->SetBinError(4,70);
   HitRatio_BottomandSide__1->SetBinError(5,69);
   HitRatio_BottomandSide__1->SetBinError(6,74);
   HitRatio_BottomandSide__1->SetBinError(7,72);
   HitRatio_BottomandSide__1->SetBinError(8,65);
   HitRatio_BottomandSide__1->SetBinError(9,74);
   HitRatio_BottomandSide__1->SetBinError(10,63);
   HitRatio_BottomandSide__1->SetBinError(11,65);
   HitRatio_BottomandSide__1->SetBinError(12,72);
   HitRatio_BottomandSide__1->SetBinError(13,72);
   HitRatio_BottomandSide__1->SetBinError(14,67);
   HitRatio_BottomandSide__1->SetBinError(15,67);
   HitRatio_BottomandSide__1->SetBinError(16,59);
   HitRatio_BottomandSide__1->SetBinError(17,64);
   HitRatio_BottomandSide__1->SetBinError(18,74);
   HitRatio_BottomandSide__1->SetBinError(19,75);
   HitRatio_BottomandSide__1->SetBinError(20,65);
   HitRatio_BottomandSide__1->SetBinError(21,52);
   HitRatio_BottomandSide__1->SetEntries(21);
   HitRatio_BottomandSide__1->SetStats(0);

   ci = TColor::GetColor("#920a41");
   HitRatio_BottomandSide__1->SetLineColor(ci);
   HitRatio_BottomandSide__1->GetXaxis()->SetLabelFont(132);
   HitRatio_BottomandSide__1->GetXaxis()->SetTitleOffset(1);
   HitRatio_BottomandSide__1->GetXaxis()->SetTitleFont(132);
   HitRatio_BottomandSide__1->GetYaxis()->SetLabelFont(132);
   HitRatio_BottomandSide__1->GetYaxis()->SetTitleFont(132);
   HitRatio_BottomandSide__1->GetZaxis()->SetLabelFont(132);
   HitRatio_BottomandSide__1->GetZaxis()->SetTitleOffset(1);
   HitRatio_BottomandSide__1->GetZaxis()->SetTitleFont(132);
   HitRatio_BottomandSide__1->Draw("HistSame");
   
   TH1D *HitRatio_TopandSide__2 = new TH1D("HitRatio_TopandSide__2","HitRatio_TopandSide",21,5,26);
   HitRatio_TopandSide__2->SetBinContent(1,67);
   HitRatio_TopandSide__2->SetBinContent(2,74);
   HitRatio_TopandSide__2->SetBinContent(3,67);
   HitRatio_TopandSide__2->SetBinContent(4,70);
   HitRatio_TopandSide__2->SetBinContent(5,69);
   HitRatio_TopandSide__2->SetBinContent(6,74);
   HitRatio_TopandSide__2->SetBinContent(7,72);
   HitRatio_TopandSide__2->SetBinContent(8,65);
   HitRatio_TopandSide__2->SetBinContent(9,74);
   HitRatio_TopandSide__2->SetBinContent(10,63);
   HitRatio_TopandSide__2->SetBinContent(11,65);
   HitRatio_TopandSide__2->SetBinContent(12,72);
   HitRatio_TopandSide__2->SetBinContent(13,71);
   HitRatio_TopandSide__2->SetBinContent(14,67);
   HitRatio_TopandSide__2->SetBinContent(15,67);
   HitRatio_TopandSide__2->SetBinContent(16,59);
   HitRatio_TopandSide__2->SetBinContent(17,64);
   HitRatio_TopandSide__2->SetBinContent(18,74);
   HitRatio_TopandSide__2->SetBinContent(19,75);
   HitRatio_TopandSide__2->SetBinContent(20,65);
   HitRatio_TopandSide__2->SetBinContent(21,52);
   HitRatio_TopandSide__2->SetBinError(1,67);
   HitRatio_TopandSide__2->SetBinError(2,74);
   HitRatio_TopandSide__2->SetBinError(3,67);
   HitRatio_TopandSide__2->SetBinError(4,70);
   HitRatio_TopandSide__2->SetBinError(5,69);
   HitRatio_TopandSide__2->SetBinError(6,74);
   HitRatio_TopandSide__2->SetBinError(7,72);
   HitRatio_TopandSide__2->SetBinError(8,65);
   HitRatio_TopandSide__2->SetBinError(9,74);
   HitRatio_TopandSide__2->SetBinError(10,63);
   HitRatio_TopandSide__2->SetBinError(11,65);
   HitRatio_TopandSide__2->SetBinError(12,72);
   HitRatio_TopandSide__2->SetBinError(13,71);
   HitRatio_TopandSide__2->SetBinError(14,67);
   HitRatio_TopandSide__2->SetBinError(15,67);
   HitRatio_TopandSide__2->SetBinError(16,59);
   HitRatio_TopandSide__2->SetBinError(17,64);
   HitRatio_TopandSide__2->SetBinError(18,74);
   HitRatio_TopandSide__2->SetBinError(19,75);
   HitRatio_TopandSide__2->SetBinError(20,65);
   HitRatio_TopandSide__2->SetBinError(21,52);
   HitRatio_TopandSide__2->SetEntries(21);
   HitRatio_TopandSide__2->SetStats(0);

   ci = TColor::GetColor("#3880df");
   HitRatio_TopandSide__2->SetLineColor(ci);
   HitRatio_TopandSide__2->GetXaxis()->SetLabelFont(132);
   HitRatio_TopandSide__2->GetXaxis()->SetTitleOffset(1);
   HitRatio_TopandSide__2->GetXaxis()->SetTitleFont(132);
   HitRatio_TopandSide__2->GetYaxis()->SetLabelFont(132);
   HitRatio_TopandSide__2->GetYaxis()->SetTitleFont(132);
   HitRatio_TopandSide__2->GetZaxis()->SetLabelFont(132);
   HitRatio_TopandSide__2->GetZaxis()->SetTitleOffset(1);
   HitRatio_TopandSide__2->GetZaxis()->SetTitleFont(132);
   HitRatio_TopandSide__2->Draw("HistSame");
   
   TH1D *HitRatio_TopandBottom__3 = new TH1D("HitRatio_TopandBottom__3","HitRatio_TopandBottom",21,5,26);
   HitRatio_TopandBottom__3->SetBinContent(1,67);
   HitRatio_TopandBottom__3->SetBinContent(2,74);
   HitRatio_TopandBottom__3->SetBinContent(3,67);
   HitRatio_TopandBottom__3->SetBinContent(4,70);
   HitRatio_TopandBottom__3->SetBinContent(5,69);
   HitRatio_TopandBottom__3->SetBinContent(6,74);
   HitRatio_TopandBottom__3->SetBinContent(7,72);
   HitRatio_TopandBottom__3->SetBinContent(8,65);
   HitRatio_TopandBottom__3->SetBinContent(9,74);
   HitRatio_TopandBottom__3->SetBinContent(10,63);
   HitRatio_TopandBottom__3->SetBinContent(11,65);
   HitRatio_TopandBottom__3->SetBinContent(12,72);
   HitRatio_TopandBottom__3->SetBinContent(13,71);
   HitRatio_TopandBottom__3->SetBinContent(14,67);
   HitRatio_TopandBottom__3->SetBinContent(15,66);
   HitRatio_TopandBottom__3->SetBinContent(16,59);
   HitRatio_TopandBottom__3->SetBinContent(17,64);
   HitRatio_TopandBottom__3->SetBinContent(18,74);
   HitRatio_TopandBottom__3->SetBinContent(19,75);
   HitRatio_TopandBottom__3->SetBinContent(20,65);
   HitRatio_TopandBottom__3->SetBinContent(21,52);
   HitRatio_TopandBottom__3->SetBinError(1,67);
   HitRatio_TopandBottom__3->SetBinError(2,74);
   HitRatio_TopandBottom__3->SetBinError(3,67);
   HitRatio_TopandBottom__3->SetBinError(4,70);
   HitRatio_TopandBottom__3->SetBinError(5,69);
   HitRatio_TopandBottom__3->SetBinError(6,74);
   HitRatio_TopandBottom__3->SetBinError(7,72);
   HitRatio_TopandBottom__3->SetBinError(8,65);
   HitRatio_TopandBottom__3->SetBinError(9,74);
   HitRatio_TopandBottom__3->SetBinError(10,63);
   HitRatio_TopandBottom__3->SetBinError(11,65);
   HitRatio_TopandBottom__3->SetBinError(12,72);
   HitRatio_TopandBottom__3->SetBinError(13,71);
   HitRatio_TopandBottom__3->SetBinError(14,67);
   HitRatio_TopandBottom__3->SetBinError(15,66);
   HitRatio_TopandBottom__3->SetBinError(16,59);
   HitRatio_TopandBottom__3->SetBinError(17,64);
   HitRatio_TopandBottom__3->SetBinError(18,74);
   HitRatio_TopandBottom__3->SetBinError(19,75);
   HitRatio_TopandBottom__3->SetBinError(20,65);
   HitRatio_TopandBottom__3->SetBinError(21,52);
   HitRatio_TopandBottom__3->SetEntries(21);
   HitRatio_TopandBottom__3->SetStats(0);

   ci = TColor::GetColor("#ebc242");
   HitRatio_TopandBottom__3->SetLineColor(ci);
   HitRatio_TopandBottom__3->GetXaxis()->SetLabelFont(132);
   HitRatio_TopandBottom__3->GetXaxis()->SetTitleOffset(1);
   HitRatio_TopandBottom__3->GetXaxis()->SetTitleFont(132);
   HitRatio_TopandBottom__3->GetYaxis()->SetLabelFont(132);
   HitRatio_TopandBottom__3->GetYaxis()->SetTitleFont(132);
   HitRatio_TopandBottom__3->GetZaxis()->SetLabelFont(132);
   HitRatio_TopandBottom__3->GetZaxis()->SetTitleOffset(1);
   HitRatio_TopandBottom__3->GetZaxis()->SetTitleFont(132);
   HitRatio_TopandBottom__3->Draw("HistSame");
   
   TH1D *HitRatio_Side__4 = new TH1D("HitRatio_Side__4","HitRatio_Side",21,5,26);
   HitRatio_Side__4->SetBinContent(1,58);
   HitRatio_Side__4->SetBinContent(2,56);
   HitRatio_Side__4->SetBinContent(3,53);
   HitRatio_Side__4->SetBinContent(4,58);
   HitRatio_Side__4->SetBinContent(5,55);
   HitRatio_Side__4->SetBinContent(6,56);
   HitRatio_Side__4->SetBinContent(7,52);
   HitRatio_Side__4->SetBinContent(8,53);
   HitRatio_Side__4->SetBinContent(9,54);
   HitRatio_Side__4->SetBinContent(10,45);
   HitRatio_Side__4->SetBinContent(11,47);
   HitRatio_Side__4->SetBinContent(12,55);
   HitRatio_Side__4->SetBinContent(13,52);
   HitRatio_Side__4->SetBinContent(14,50);
   HitRatio_Side__4->SetBinContent(15,51);
   HitRatio_Side__4->SetBinContent(16,43);
   HitRatio_Side__4->SetBinContent(17,43);
   HitRatio_Side__4->SetBinContent(18,59);
   HitRatio_Side__4->SetBinContent(19,61);
   HitRatio_Side__4->SetBinContent(20,50);
   HitRatio_Side__4->SetBinContent(21,34);
   HitRatio_Side__4->SetBinError(1,58);
   HitRatio_Side__4->SetBinError(2,56);
   HitRatio_Side__4->SetBinError(3,53);
   HitRatio_Side__4->SetBinError(4,58);
   HitRatio_Side__4->SetBinError(5,55);
   HitRatio_Side__4->SetBinError(6,56);
   HitRatio_Side__4->SetBinError(7,52);
   HitRatio_Side__4->SetBinError(8,53);
   HitRatio_Side__4->SetBinError(9,54);
   HitRatio_Side__4->SetBinError(10,45);
   HitRatio_Side__4->SetBinError(11,47);
   HitRatio_Side__4->SetBinError(12,55);
   HitRatio_Side__4->SetBinError(13,52);
   HitRatio_Side__4->SetBinError(14,50);
   HitRatio_Side__4->SetBinError(15,51);
   HitRatio_Side__4->SetBinError(16,43);
   HitRatio_Side__4->SetBinError(17,43);
   HitRatio_Side__4->SetBinError(18,59);
   HitRatio_Side__4->SetBinError(19,61);
   HitRatio_Side__4->SetBinError(20,50);
   HitRatio_Side__4->SetBinError(21,34);
   HitRatio_Side__4->SetEntries(21);
   HitRatio_Side__4->SetStats(0);

   ci = TColor::GetColor("#295fa6");
   HitRatio_Side__4->SetLineColor(ci);
   HitRatio_Side__4->GetXaxis()->SetLabelFont(132);
   HitRatio_Side__4->GetXaxis()->SetTitleOffset(1);
   HitRatio_Side__4->GetXaxis()->SetTitleFont(132);
   HitRatio_Side__4->GetYaxis()->SetLabelFont(132);
   HitRatio_Side__4->GetYaxis()->SetTitleFont(132);
   HitRatio_Side__4->GetZaxis()->SetLabelFont(132);
   HitRatio_Side__4->GetZaxis()->SetTitleOffset(1);
   HitRatio_Side__4->GetZaxis()->SetTitleFont(132);
   HitRatio_Side__4->Draw("HistSame");
   
   TH1D *HitRatio_Top__5 = new TH1D("HitRatio_Top__5","HitRatio_Top",21,5,26);
   HitRatio_Top__5->SetBinContent(1,25);
   HitRatio_Top__5->SetBinContent(2,29);
   HitRatio_Top__5->SetBinContent(3,29);
   HitRatio_Top__5->SetBinContent(4,29);
   HitRatio_Top__5->SetBinContent(5,28);
   HitRatio_Top__5->SetBinContent(6,25);
   HitRatio_Top__5->SetBinContent(7,32);
   HitRatio_Top__5->SetBinContent(8,31);
   HitRatio_Top__5->SetBinContent(9,25);
   HitRatio_Top__5->SetBinContent(10,21);
   HitRatio_Top__5->SetBinContent(11,24);
   HitRatio_Top__5->SetBinContent(12,31);
   HitRatio_Top__5->SetBinContent(13,28);
   HitRatio_Top__5->SetBinContent(14,26);
   HitRatio_Top__5->SetBinContent(15,19);
   HitRatio_Top__5->SetBinContent(16,21);
   HitRatio_Top__5->SetBinContent(17,22);
   HitRatio_Top__5->SetBinContent(18,30);
   HitRatio_Top__5->SetBinContent(19,28);
   HitRatio_Top__5->SetBinContent(20,34);
   HitRatio_Top__5->SetBinContent(21,26);
   HitRatio_Top__5->SetBinError(1,25);
   HitRatio_Top__5->SetBinError(2,29);
   HitRatio_Top__5->SetBinError(3,29);
   HitRatio_Top__5->SetBinError(4,29);
   HitRatio_Top__5->SetBinError(5,28);
   HitRatio_Top__5->SetBinError(6,25);
   HitRatio_Top__5->SetBinError(7,32);
   HitRatio_Top__5->SetBinError(8,31);
   HitRatio_Top__5->SetBinError(9,25);
   HitRatio_Top__5->SetBinError(10,21);
   HitRatio_Top__5->SetBinError(11,24);
   HitRatio_Top__5->SetBinError(12,31);
   HitRatio_Top__5->SetBinError(13,28);
   HitRatio_Top__5->SetBinError(14,26);
   HitRatio_Top__5->SetBinError(15,19);
   HitRatio_Top__5->SetBinError(16,21);
   HitRatio_Top__5->SetBinError(17,22);
   HitRatio_Top__5->SetBinError(18,30);
   HitRatio_Top__5->SetBinError(19,28);
   HitRatio_Top__5->SetBinError(20,34);
   HitRatio_Top__5->SetBinError(21,26);
   HitRatio_Top__5->SetEntries(21);
   HitRatio_Top__5->SetStats(0);

   ci = TColor::GetColor("#0aa67a");
   HitRatio_Top__5->SetLineColor(ci);
   HitRatio_Top__5->GetXaxis()->SetLabelFont(132);
   HitRatio_Top__5->GetXaxis()->SetTitleOffset(1);
   HitRatio_Top__5->GetXaxis()->SetTitleFont(132);
   HitRatio_Top__5->GetYaxis()->SetLabelFont(132);
   HitRatio_Top__5->GetYaxis()->SetTitleFont(132);
   HitRatio_Top__5->GetZaxis()->SetLabelFont(132);
   HitRatio_Top__5->GetZaxis()->SetTitleOffset(1);
   HitRatio_Top__5->GetZaxis()->SetTitleFont(132);
   HitRatio_Top__5->Draw("HistSame");
   
   TH1D *HitRatio_Bottom__6 = new TH1D("HitRatio_Bottom__6","HitRatio_Bottom",21,5,26);
   HitRatio_Bottom__6->SetBinContent(1,22);
   HitRatio_Bottom__6->SetBinContent(2,23);
   HitRatio_Bottom__6->SetBinContent(3,22);
   HitRatio_Bottom__6->SetBinContent(4,20);
   HitRatio_Bottom__6->SetBinContent(5,21);
   HitRatio_Bottom__6->SetBinContent(6,18);
   HitRatio_Bottom__6->SetBinContent(7,23);
   HitRatio_Bottom__6->SetBinContent(8,28);
   HitRatio_Bottom__6->SetBinContent(9,17);
   HitRatio_Bottom__6->SetBinContent(10,17);
   HitRatio_Bottom__6->SetBinContent(11,19);
   HitRatio_Bottom__6->SetBinContent(12,24);
   HitRatio_Bottom__6->SetBinContent(13,14);
   HitRatio_Bottom__6->SetBinContent(14,22);
   HitRatio_Bottom__6->SetBinContent(15,17);
   HitRatio_Bottom__6->SetBinContent(16,8);
   HitRatio_Bottom__6->SetBinContent(17,13);
   HitRatio_Bottom__6->SetBinContent(18,23);
   HitRatio_Bottom__6->SetBinContent(19,26);
   HitRatio_Bottom__6->SetBinContent(20,28);
   HitRatio_Bottom__6->SetBinContent(21,17);
   HitRatio_Bottom__6->SetBinError(1,22);
   HitRatio_Bottom__6->SetBinError(2,23);
   HitRatio_Bottom__6->SetBinError(3,22);
   HitRatio_Bottom__6->SetBinError(4,20);
   HitRatio_Bottom__6->SetBinError(5,21);
   HitRatio_Bottom__6->SetBinError(6,18);
   HitRatio_Bottom__6->SetBinError(7,23);
   HitRatio_Bottom__6->SetBinError(8,28);
   HitRatio_Bottom__6->SetBinError(9,17);
   HitRatio_Bottom__6->SetBinError(10,17);
   HitRatio_Bottom__6->SetBinError(11,19);
   HitRatio_Bottom__6->SetBinError(12,24);
   HitRatio_Bottom__6->SetBinError(13,14);
   HitRatio_Bottom__6->SetBinError(14,22);
   HitRatio_Bottom__6->SetBinError(15,17);
   HitRatio_Bottom__6->SetBinError(16,8);
   HitRatio_Bottom__6->SetBinError(17,13);
   HitRatio_Bottom__6->SetBinError(18,23);
   HitRatio_Bottom__6->SetBinError(19,26);
   HitRatio_Bottom__6->SetBinError(20,28);
   HitRatio_Bottom__6->SetBinError(21,17);
   HitRatio_Bottom__6->SetEntries(21);
   HitRatio_Bottom__6->SetStats(0);

   ci = TColor::GetColor("#d9303e");
   HitRatio_Bottom__6->SetLineColor(ci);
   HitRatio_Bottom__6->GetXaxis()->SetLabelFont(132);
   HitRatio_Bottom__6->GetXaxis()->SetTitleOffset(1);
   HitRatio_Bottom__6->GetXaxis()->SetTitleFont(132);
   HitRatio_Bottom__6->GetYaxis()->SetLabelFont(132);
   HitRatio_Bottom__6->GetYaxis()->SetTitleFont(132);
   HitRatio_Bottom__6->GetZaxis()->SetLabelFont(132);
   HitRatio_Bottom__6->GetZaxis()->SetTitleOffset(1);
   HitRatio_Bottom__6->GetZaxis()->SetTitleFont(132);
   HitRatio_Bottom__6->Draw("HistSame");
   
   TLegend *leg = new TLegend(0.8175182,0.7556818,0.9702815,0.9715909,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetTextFont(132);
   leg->SetTextSize(0.035);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("HitRatio_BottomandSide","Bottom & Side","lf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#920a41");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   entry=leg->AddEntry("HitRatio_TopandSide","Top & Side","lf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#3880df");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   entry=leg->AddEntry("HitRatio_TopandBottom","Top & Bottom","lf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ebc242");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   entry=leg->AddEntry("HitRatio_Side","Side","lf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#295fa6");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   entry=leg->AddEntry("HitRatio_Top","Top","lf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0aa67a");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   entry=leg->AddEntry("HitRatio_Bottom","Bottom","lf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#d9303e");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(132);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.2381752,0.918,0.7618248,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(132);
   TText *pt_LaTex = pt->AddText("Fission's Detectors' Efficiencies");
   pt->Draw();
   cTheta->Modified();
   cTheta->cd();
   cTheta->SetSelected(cTheta);
}
